site_name: PembrokePSqman
repo_url: https://github.com/jpsider/PembrokePSqman
theme: readthedocs
pages:
- Home: index.md
- PembrokePSqman Basics:
  - What is PembrokePSqman: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
